import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import java.util.*

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id ("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    mavenLocal()
    maven("https://repo.papermc.io/repository/maven-public/")

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.bstats:bstats-bukkit:2.2.1")
    compileOnly("io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT")
    implementation("net.kyori:adventure-platform-bukkit:4.3.2")
}
java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}
group = "net.multylands.duels"
version = "v1.26"
description = "Duels"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
tasks {
    shadowJar {
        // See https://github.com/johnrengelman/shadow/issues/448
        project.configurations.implementation.get().isCanBeResolved = true

        configurations = listOf(project.configurations.runtimeClasspath.get())
        relocate("org.bstats", project.group.toString())
    }
}
tasks.processResources {
    outputs.upToDateWhen { false }
    filesMatching("plugin.yml") {
        expand(mapOf("version" to project.version))
    }
}
tasks {
    register<Copy>("copyToServer") {
        dependsOn(shadowJar)
        from(shadowJar)
        into("C:/Users/green/Desktop/Test Server/plugins")
        this@register.rename("-all", "")
    }
}
