spawn_location:
  ==: org.bukkit.Location
  world: world
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0
#Max duel time. After this time goes both players will be teleported to the spawn.
max_duel_time_minutes: 10
#After the duel ends how many seconds should we give the
#winner to pick up the loser's item before teleporting them to the spawn
time_to_pick_up_items: 10

#Delay in ticks. We use this after the duel ends to reset player's shield blocking delay. Don't touch if you don't know what this does.
default-shield-blocking-delay: 5

#commands allowed when you are spectating the duel
spectator_whitelist_mode: true
commands_blacklisted_or_whitelisted_in_spectator:
  - spawn
  - leavespectator
#here you can toggle which modules will be enabled/disabled in the server. if you turn off any, it will not show up in the
#duels GUI, so players won't be able to turn on/off that restriction.
restriction-modules:
  bow: true
  totem: true
  golden-apple: true
  enchanted-golden-apple: true
  potions: true
  shields: true
  elytra: true
  ender-pearl: true
  keep-inventory: true