spawn_location:
  ==: org.bukkit.Location
  world: world
  x: 0.0
  y: 0.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0
#Max duel time. After this time goes both players will be teleported to the spawn.
max_duel_time_minutes: 10
#After the duel ends how many seconds should we give the
#winner to pick up the loser's item before teleporting them to the spawn
time_to_pick_up_items: 10